// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.0
// source: starwars.proto

//
//protoc --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative starwars.proto

package starwars

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type None struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *None) Reset() {
	*x = None{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *None) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*None) ProtoMessage() {}

func (x *None) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use None.ProtoReflect.Descriptor instead.
func (*None) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{0}
}

type Reply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *Reply) Reset() {
	*x = Reply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reply) ProtoMessage() {}

func (x *Reply) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reply.ProtoReflect.Descriptor instead.
func (*Reply) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{1}
}

func (x *Reply) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

type FulcrumID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *FulcrumID) Reset() {
	*x = FulcrumID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FulcrumID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FulcrumID) ProtoMessage() {}

func (x *FulcrumID) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FulcrumID.ProtoReflect.Descriptor instead.
func (*FulcrumID) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{2}
}

func (x *FulcrumID) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type Fulcrums struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	F0 string `protobuf:"bytes,1,opt,name=F0,proto3" json:"F0,omitempty"`
	F1 string `protobuf:"bytes,2,opt,name=F1,proto3" json:"F1,omitempty"`
	F2 string `protobuf:"bytes,3,opt,name=F2,proto3" json:"F2,omitempty"`
}

func (x *Fulcrums) Reset() {
	*x = Fulcrums{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Fulcrums) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fulcrums) ProtoMessage() {}

func (x *Fulcrums) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fulcrums.ProtoReflect.Descriptor instead.
func (*Fulcrums) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{3}
}

func (x *Fulcrums) GetF0() string {
	if x != nil {
		return x.F0
	}
	return ""
}

func (x *Fulcrums) GetF1() string {
	if x != nil {
		return x.F1
	}
	return ""
}

func (x *Fulcrums) GetF2() string {
	if x != nil {
		return x.F2
	}
	return ""
}

type Register struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanetName  string `protobuf:"bytes,1,opt,name=PlanetName,proto3" json:"PlanetName,omitempty"`
	CityName    string `protobuf:"bytes,2,opt,name=CityName,proto3" json:"CityName,omitempty"`
	RebelCount  string `protobuf:"bytes,3,opt,name=RebelCount,proto3" json:"RebelCount,omitempty"`
	NewCityName string `protobuf:"bytes,4,opt,name=NewCityName,proto3" json:"NewCityName,omitempty"`
}

func (x *Register) Reset() {
	*x = Register{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Register) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Register) ProtoMessage() {}

func (x *Register) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Register.ProtoReflect.Descriptor instead.
func (*Register) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{4}
}

func (x *Register) GetPlanetName() string {
	if x != nil {
		return x.PlanetName
	}
	return ""
}

func (x *Register) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *Register) GetRebelCount() string {
	if x != nil {
		return x.RebelCount
	}
	return ""
}

func (x *Register) GetNewCityName() string {
	if x != nil {
		return x.NewCityName
	}
	return ""
}

type RequestRebel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlanetName string `protobuf:"bytes,1,opt,name=PlanetName,proto3" json:"PlanetName,omitempty"`
	CityName   string `protobuf:"bytes,2,opt,name=CityName,proto3" json:"CityName,omitempty"`
}

func (x *RequestRebel) Reset() {
	*x = RequestRebel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRebel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRebel) ProtoMessage() {}

func (x *RequestRebel) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRebel.ProtoReflect.Descriptor instead.
func (*RequestRebel) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{5}
}

func (x *RequestRebel) GetPlanetName() string {
	if x != nil {
		return x.PlanetName
	}
	return ""
}

func (x *RequestRebel) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

type Command struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command  string `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Planet   string `protobuf:"bytes,2,opt,name=planet,proto3" json:"planet,omitempty"`
	City     string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	NewValue string `protobuf:"bytes,4,opt,name=newValue,proto3" json:"newValue,omitempty"`
}

func (x *Command) Reset() {
	*x = Command{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{6}
}

func (x *Command) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Command) GetPlanet() string {
	if x != nil {
		return x.Planet
	}
	return ""
}

func (x *Command) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Command) GetNewValue() string {
	if x != nil {
		return x.NewValue
	}
	return ""
}

type Changes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Log   string `protobuf:"bytes,1,opt,name=Log,proto3" json:"Log,omitempty"`
	Clock []byte `protobuf:"bytes,2,opt,name=Clock,proto3" json:"Clock,omitempty"`
}

func (x *Changes) Reset() {
	*x = Changes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_starwars_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Changes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Changes) ProtoMessage() {}

func (x *Changes) ProtoReflect() protoreflect.Message {
	mi := &file_starwars_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Changes.ProtoReflect.Descriptor instead.
func (*Changes) Descriptor() ([]byte, []int) {
	return file_starwars_proto_rawDescGZIP(), []int{7}
}

func (x *Changes) GetLog() string {
	if x != nil {
		return x.Log
	}
	return ""
}

func (x *Changes) GetClock() []byte {
	if x != nil {
		return x.Clock
	}
	return nil
}

var File_starwars_proto protoreflect.FileDescriptor

var file_starwars_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x22, 0x06, 0x0a, 0x04, 0x4e, 0x6f,
	0x6e, 0x65, 0x22, 0x1d, 0x0a, 0x05, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x70, 0x6c, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x1b, 0x0a, 0x09, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x49, 0x44, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x22, 0x3a,
	0x0a, 0x08, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x30,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x46, 0x30, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x31,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x46, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x46, 0x32,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x46, 0x32, 0x22, 0x88, 0x01, 0x0a, 0x08, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61,
	0x6e, 0x65, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x4e, 0x65, 0x77, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x4e, 0x65, 0x77, 0x43, 0x69, 0x74,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x65, 0x62, 0x65, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x69, 0x74, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x22, 0x6b, 0x0a, 0x07, 0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69,
	0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x6e, 0x65, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31,
	0x0a, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x4c, 0x6f, 0x67,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4c, 0x6f, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x43,
	0x6c, 0x6f, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x43, 0x6c, 0x6f, 0x63,
	0x6b, 0x32, 0xeb, 0x01, 0x0a, 0x06, 0x42, 0x72, 0x6f, 0x6b, 0x65, 0x72, 0x12, 0x37, 0x0a, 0x0d,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x13, 0x2e,
	0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d,
	0x49, 0x44, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0b, 0x47, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x61, 0x6e, 0x64, 0x12, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61,
	0x72, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0d, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x73, 0x12, 0x16, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65,
	0x62, 0x65, 0x6c, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x73, 0x12, 0x0e, 0x2e, 0x73, 0x74, 0x61, 0x72,
	0x77, 0x61, 0x72, 0x73, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x72,
	0x77, 0x61, 0x72, 0x73, 0x2e, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x73, 0x22, 0x00, 0x32,
	0x86, 0x03, 0x0a, 0x07, 0x46, 0x75, 0x6c, 0x63, 0x72, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x07, 0x41,
	0x64, 0x64, 0x43, 0x69, 0x74, 0x79, 0x12, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72,
	0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61,
	0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a,
	0x0f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x35, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x12, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72,
	0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0a, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x43, 0x69, 0x74, 0x79, 0x12, 0x12, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61,
	0x72, 0x73, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x1a, 0x0f, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3a,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x73, 0x12,
	0x16, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x65, 0x62, 0x65, 0x6c, 0x1a, 0x0f, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61,
	0x72, 0x73, 0x2e, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0d, 0x52, 0x65,
	0x70, 0x6f, 0x72, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x1a, 0x11, 0x2e, 0x73, 0x74,
	0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x36, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x69, 0x65, 0x76, 0x65, 0x4e, 0x65, 0x77, 0x43, 0x6c,
	0x6f, 0x63, 0x6b, 0x12, 0x11, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72, 0x73, 0x2e, 0x43,
	0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x1a, 0x0e, 0x2e, 0x73, 0x74, 0x61, 0x72, 0x77, 0x61, 0x72,
	0x73, 0x2e, 0x4e, 0x6f, 0x6e, 0x65, 0x22, 0x00, 0x42, 0x0b, 0x5a, 0x09, 0x2f, 0x73, 0x74, 0x61,
	0x72, 0x77, 0x61, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_starwars_proto_rawDescOnce sync.Once
	file_starwars_proto_rawDescData = file_starwars_proto_rawDesc
)

func file_starwars_proto_rawDescGZIP() []byte {
	file_starwars_proto_rawDescOnce.Do(func() {
		file_starwars_proto_rawDescData = protoimpl.X.CompressGZIP(file_starwars_proto_rawDescData)
	})
	return file_starwars_proto_rawDescData
}

var file_starwars_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_starwars_proto_goTypes = []interface{}{
	(*None)(nil),         // 0: starwars.None
	(*Reply)(nil),        // 1: starwars.Reply
	(*FulcrumID)(nil),    // 2: starwars.FulcrumID
	(*Fulcrums)(nil),     // 3: starwars.Fulcrums
	(*Register)(nil),     // 4: starwars.Register
	(*RequestRebel)(nil), // 5: starwars.RequestRebel
	(*Command)(nil),      // 6: starwars.Command
	(*Changes)(nil),      // 7: starwars.Changes
}
var file_starwars_proto_depIdxs = []int32{
	2,  // 0: starwars.Broker.ReportFulcrum:input_type -> starwars.FulcrumID
	6,  // 1: starwars.Broker.GiveCommand:input_type -> starwars.Command
	5,  // 2: starwars.Broker.RequestRebels:input_type -> starwars.RequestRebel
	0,  // 3: starwars.Broker.RequestFulcrums:input_type -> starwars.None
	4,  // 4: starwars.Fulcrum.AddCity:input_type -> starwars.Register
	4,  // 5: starwars.Fulcrum.UpdateName:input_type -> starwars.Register
	4,  // 6: starwars.Fulcrum.UpdateNumber:input_type -> starwars.Register
	4,  // 7: starwars.Fulcrum.DeleteCity:input_type -> starwars.Register
	5,  // 8: starwars.Fulcrum.RequestRebels:input_type -> starwars.RequestRebel
	0,  // 9: starwars.Fulcrum.ReportChanges:input_type -> starwars.None
	7,  // 10: starwars.Fulcrum.RecieveNewClock:input_type -> starwars.Changes
	1,  // 11: starwars.Broker.ReportFulcrum:output_type -> starwars.Reply
	1,  // 12: starwars.Broker.GiveCommand:output_type -> starwars.Reply
	1,  // 13: starwars.Broker.RequestRebels:output_type -> starwars.Reply
	3,  // 14: starwars.Broker.RequestFulcrums:output_type -> starwars.Fulcrums
	1,  // 15: starwars.Fulcrum.AddCity:output_type -> starwars.Reply
	1,  // 16: starwars.Fulcrum.UpdateName:output_type -> starwars.Reply
	1,  // 17: starwars.Fulcrum.UpdateNumber:output_type -> starwars.Reply
	1,  // 18: starwars.Fulcrum.DeleteCity:output_type -> starwars.Reply
	1,  // 19: starwars.Fulcrum.RequestRebels:output_type -> starwars.Reply
	7,  // 20: starwars.Fulcrum.ReportChanges:output_type -> starwars.Changes
	0,  // 21: starwars.Fulcrum.RecieveNewClock:output_type -> starwars.None
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_starwars_proto_init() }
func file_starwars_proto_init() {
	if File_starwars_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_starwars_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*None); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FulcrumID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Fulcrums); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Register); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRebel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Command); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_starwars_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Changes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_starwars_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_starwars_proto_goTypes,
		DependencyIndexes: file_starwars_proto_depIdxs,
		MessageInfos:      file_starwars_proto_msgTypes,
	}.Build()
	File_starwars_proto = out.File
	file_starwars_proto_rawDesc = nil
	file_starwars_proto_goTypes = nil
	file_starwars_proto_depIdxs = nil
}
